# Uncomment the next line to define a global platform for your project

inhibit_all_warnings!
pod 'AFNetworking', '3.1.0'
pod 'SDWebImage',  '4.0.0'
pod 'MJExtension', '3.0.10'
pod 'MJRefresh'
pod 'MBProgressHUD', '0.9.2'
pod 'IQKeyboardManager'
pod 'Masonry', '1.0.0'
pod 'SDCycleScrollView','1.75'
pod 'HUPhotoBrowser'
pod 'DZNEmptyDataSet'
pod 'PPBadgeView'
pod 'PGPickerView', '1.3.4'
pod 'WebViewJavascriptBridge'
pod 'PPNetworkHelper'
platform :ios, '9.0'

target 'GHTestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GHTestDemo

end
